---
deployment:
  tasks:
    - export DEPLOYPATH=/home/amelkyau/ind-checker-server.ameliamargaurite.dev
    - /bin/cp index.js $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp package-lock.json $DEPLOYPATH
